export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'
export const DISPLAY_PRODUCT = 'DISPLAY_PRODUCT'
export const CLEAR_SINGLE_PRODUCT = 'CLEAR_SINGLE_PRODUCT'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const SUBTRACT_QUANTITY = 'SUBTRACT_QUANTITY'
export const SET_ERROR = 'SET_ERROR'
export const DISMISS_ERROR = 'DISMISS_ERROR'
export const DISMISS_SUCCESS = 'DISMISS_SUCCESS'
export const OPEN_SIDE_PANEL = 'OPEN_SIDE_PANEL'
export const CLOSE_SIDE_PANEL = 'CLOSE_SIDE_PANEL'

export const sidePanels = {
  NONE: 'NONE',
  SEARCH: 'SEARCH',
  CART: 'CART'
}